version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 6.0-focal, 7.0-bullseye, 8.0-bookworm , 9.0-bookworm, 10.0-noble (default)
        VARIANT: "10.0-noble"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    hostname: sqlserver2025-librarydb
    container_name: sqlserver2025-librarydb
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      # Developer edition (default) - full features, free for dev
      MSSQL_PID: Developer
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    # Add "forwardPorts": ["1433"] to **devcontainer.json** to forward MSSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)